/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ordemservico.view;

import java.util.ArrayList;

/**
 *
 * @author aluno
 */
public class FrameAcessoTelas extends javax.swing.JFrame {

    /**
     * Creates new form FrameAcessoTelas
     */
    public FrameAcessoTelas() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btAcessoServico = new javax.swing.JButton();
        btAcessoVeiculo = new javax.swing.JButton();
        btGerarRelatorio = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btAcessoCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btAcessoServico.setBackground(new java.awt.Color(0, 0, 0));
        btAcessoServico.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btAcessoServico.setForeground(new java.awt.Color(255, 255, 255));
        btAcessoServico.setText("Registrar Serviços");
        btAcessoServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAcessoServicoActionPerformed(evt);
            }
        });

        btAcessoVeiculo.setBackground(new java.awt.Color(0, 0, 0));
        btAcessoVeiculo.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btAcessoVeiculo.setForeground(new java.awt.Color(255, 255, 255));
        btAcessoVeiculo.setText("Registrar Veículos");
        btAcessoVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAcessoVeiculoActionPerformed(evt);
            }
        });

        btGerarRelatorio.setBackground(new java.awt.Color(0, 0, 0));
        btGerarRelatorio.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btGerarRelatorio.setForeground(new java.awt.Color(255, 255, 255));
        btGerarRelatorio.setText("Gerar Relatório");
        btGerarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGerarRelatorioActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setText("Acessos");

        btAcessoCliente.setBackground(new java.awt.Color(0, 0, 0));
        btAcessoCliente.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btAcessoCliente.setForeground(new java.awt.Color(255, 255, 255));
        btAcessoCliente.setText("Registrar Cliente");
        btAcessoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAcessoClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btGerarRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btAcessoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(24, 24, 24)
                                    .addComponent(jLabel1))
                                .addComponent(btAcessoServico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btAcessoVeiculo, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)))))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btAcessoCliente)
                .addGap(18, 18, 18)
                .addComponent(btAcessoVeiculo)
                .addGap(18, 18, 18)
                .addComponent(btAcessoServico)
                .addGap(18, 18, 18)
                .addComponent(btGerarRelatorio)
                .addGap(67, 67, 67))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAcessoServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAcessoServicoActionPerformed
        this.dispose();
        
        FrameDadosServicos acessoDadosServicos = new FrameDadosServicos();
        acessoDadosServicos.setVisible(true);
    }//GEN-LAST:event_btAcessoServicoActionPerformed

    private void btGerarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGerarRelatorioActionPerformed
        this.dispose();
        
        FrameRelatorio acessoRelatorio = new FrameRelatorio();
        acessoRelatorio.setVisible(true);
        
    }//GEN-LAST:event_btGerarRelatorioActionPerformed

    private void btAcessoVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAcessoVeiculoActionPerformed
        this.dispose();
        
        FrameDadosVeiculos acessoDadosVeiculos = new FrameDadosVeiculos();
        acessoDadosVeiculos.setVisible(true);
    }//GEN-LAST:event_btAcessoVeiculoActionPerformed

    private void btAcessoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAcessoClienteActionPerformed
        FrameDadosCliente acessoDadosCliente = new FrameDadosCliente();
        
        this.dispose();
        
        acessoDadosCliente.setVisible(true);
    }//GEN-LAST:event_btAcessoClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAcessoCliente;
    private javax.swing.JButton btAcessoServico;
    private javax.swing.JButton btAcessoVeiculo;
    private javax.swing.JButton btGerarRelatorio;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
