/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ordemservico.view;

import com.mycompany.ordemservico.controller.Controller;
import com.mycompany.ordemservico.model.Cliente;
import com.mycompany.ordemservico.model.Pecas;
import com.mycompany.ordemservico.model.Servicos;
import com.mycompany.ordemservico.model.Veiculo;
import java.math.BigDecimal;

/**
 *
 * @author aluno
 */
public class FrameRelatorio extends javax.swing.JFrame {

    /**
     * Creates new form FrameRelatorio
     */
    public FrameRelatorio() {
        initComponents();
        setLocationRelativeTo(this);
        gerarRelatorio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitulo = new javax.swing.JLabel();
        lbNomeUsuario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        epCliente = new javax.swing.JEditorPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        epVeiculo = new javax.swing.JEditorPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        epServicos = new javax.swing.JEditorPane();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        epPecas = new javax.swing.JEditorPane();
        jLabel2 = new javax.swing.JLabel();
        lbTotalValor = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbTitulo.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        lbTitulo.setText("RELATÓRIO ORDEM E SERVIÇO");

        lbNomeUsuario.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbNomeUsuario.setText("usuario");

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel1.setText("Cliente");

        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel12.setText("Veículo");

        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel13.setText("Serviços");

        epCliente.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jScrollPane1.setViewportView(epCliente);

        epVeiculo.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jScrollPane3.setViewportView(epVeiculo);

        epServicos.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jScrollPane4.setViewportView(epServicos);

        jLabel14.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel14.setText("Peças");

        epPecas.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jScrollPane5.setViewportView(epPecas);

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel2.setText("VALOR TOTAL:");

        lbTotalValor.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel3.setText("Relatorio gerado por:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane5)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbNomeUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTotalValor, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(lbTitulo))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitulo)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lbNomeUsuario)
                            .addComponent(jLabel2)))
                    .addComponent(lbTotalValor, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(193, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void gerarRelatorio() {
        BigDecimal valorTotal = new BigDecimal(0);
        
        String usuario = Controller.listaLogin.get(0).getUsuario();
        lbNomeUsuario.setText(usuario);
        lbNomeUsuario.setEnabled(false);
        
        epCliente.setEditable(false);
        epVeiculo.setEditable(false);
        epPecas.setEditable(false);
        epServicos.setEditable(false);
        lbTotalValor.setEnabled(false);
        
        if (Controller.listaCliente != null) {
            for (Cliente cliente : Controller.listaCliente) {
                epCliente.setText("Nome: " + cliente.getNome() + " - CPF: " + cliente.getCpf() 
                        + " - Contato: " + cliente.getContato() + " - Email: " + cliente.getEmail() 
                        + " - Endereço: " + cliente.getEndereco() + "\n");
            }
        }        
        
        if (Controller.listaVeiculo != null) {
            for (Veiculo veiculo : Controller.listaVeiculo) {
                epVeiculo.setText("Marca: " + veiculo.getMarca()+ " - Modelo: " + veiculo.getModelo()
                    + " - Ano: " + veiculo.getAno()+ " - Placa: " + veiculo.getPlaca()
                    + " - Cor: " + veiculo.getCor()+ "\nEstado do Veículo: " + veiculo.getEstadoVeiculo() + "\n");
            }
        }
       
        if (Controller.listaServicos != null) {
            for (Servicos servicos: Controller.listaServicos) {
                epServicos.setText(epServicos.getText() + servicos.getServico() + " - Valor: " + servicos.getValor() + "\n");

                valorTotal = valorTotal.add(servicos.getValor());
            }
        }
        
        
        if (Controller.listaPecas != null) {
            for (Pecas pecas : Controller.listaPecas) {
                if (pecas.getNomePeca() != null) {
                    epPecas.setText(epPecas.getText() + pecas.getNomePeca() + " - Quantidade: " + pecas.getQtdPeca() + " - Valor: " + pecas.getValorUnitario() + "\n");

                    valorTotal = valorTotal.add(pecas.getValorUnitario());
                }
            }
        }
        
        lbTotalValor.setText("R$ " + String.valueOf(valorTotal));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane epCliente;
    private javax.swing.JEditorPane epPecas;
    private javax.swing.JEditorPane epServicos;
    private javax.swing.JEditorPane epVeiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lbNomeUsuario;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JLabel lbTotalValor;
    // End of variables declaration//GEN-END:variables
}
