/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ordemservico.view;

import com.mycompany.ordemservico.controller.Controller;
import com.mycompany.ordemservico.model.Servicos;
import java.math.BigDecimal;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author aluno
 */
public class FrameDadosServicos extends javax.swing.JFrame {

    /**
     * Creates new form FrameDadosServicos
     */
    public FrameDadosServicos() {
        initComponents();
        setLocationRelativeTo(this);
        Controller.listaServicos = new ArrayList<>();
    }
   
            

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbServicos = new javax.swing.JLabel();
        cbFreios = new javax.swing.JCheckBox();
        cbAguaRadiador = new javax.swing.JCheckBox();
        cbTrocaOleo = new javax.swing.JCheckBox();
        cbAlinhamento = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tpDescricaoRadiador = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tpDescricaoFreio = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        tpDescricaoAlinhamento = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        tpDescricaoTrocaOleo1 = new javax.swing.JTextPane();
        cbEmbreagem = new javax.swing.JCheckBox();
        jScrollPane5 = new javax.swing.JScrollPane();
        tpDescricaoEmbreagem = new javax.swing.JTextPane();
        lbPrecoFreio = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbPrecoRadiador = new javax.swing.JLabel();
        lbPrecoOleo = new javax.swing.JLabel();
        lbPrecoAlinhamento = new javax.swing.JLabel();
        lbPrecoEmbreagem = new javax.swing.JLabel();
        btCancelar = new javax.swing.JButton();
        btAcessarPecas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbServicos.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        lbServicos.setText("SERVIÇOS:");

        cbFreios.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        cbFreios.setText("Reparo de freios (troca de pastilhas e discos)");
        cbFreios.setName("100"); // NOI18N
        cbFreios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFreiosActionPerformed(evt);
            }
        });

        cbAguaRadiador.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        cbAguaRadiador.setText("Substituição de sistema de escapamento");
        cbAguaRadiador.setName("350"); // NOI18N
        cbAguaRadiador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAguaRadiadorActionPerformed(evt);
            }
        });

        cbTrocaOleo.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        cbTrocaOleo.setText(" Troca de Correias (correia dentada, correia do alternador)");
        cbTrocaOleo.setName("280"); // NOI18N

        cbAlinhamento.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        cbAlinhamento.setText("Alinhamento e Balanceamento");
        cbAlinhamento.setName("120"); // NOI18N

        tpDescricaoRadiador.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        tpDescricaoRadiador.setText("Avaliação e correção de problemas no sistema de escapamento para baixas emissões e bom desempenho do motor.");
        jScrollPane1.setViewportView(tpDescricaoRadiador);

        tpDescricaoFreio.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        tpDescricaoFreio.setText("Este serviço envolve a avaliação e, se necessário, a substituição das pastilhas de freio e discos. Isso garante uma frenagem segura e eficiente, essencial para a segurança do veículo e de seus ocupantes.");
        jScrollPane2.setViewportView(tpDescricaoFreio);

        tpDescricaoAlinhamento.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        tpDescricaoAlinhamento.setText("Durante o alinhamento, as rodas do veículo são ajustadas de forma precisa para garantir que estejam todas apontando na mesma direção, proporcionando uma direção estável e evitando o desgaste irregular dos pneus.");
        jScrollPane3.setViewportView(tpDescricaoAlinhamento);

        tpDescricaoTrocaOleo1.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        tpDescricaoTrocaOleo1.setText("Durante este serviço, as correias do veículo, como a correia dentada e a correia do alternador, são avaliadas e, se necessário, substituídas para garantir o funcionamento adequado do motor e prevenir falhas inesperadas.");
        jScrollPane4.setViewportView(tpDescricaoTrocaOleo1);

        cbEmbreagem.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        cbEmbreagem.setText("Manutenção de embreagem");
        cbEmbreagem.setName("500"); // NOI18N
        cbEmbreagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEmbreagemActionPerformed(evt);
            }
        });

        tpDescricaoEmbreagem.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        tpDescricaoEmbreagem.setText("O mecânico verifica visualmente o estado do pedal da embreagem, cilindro mestre, cilindro escravo e linhas de fluido em busca de vazamentos, desgaste ou danos.");
        jScrollPane5.setViewportView(tpDescricaoEmbreagem);

        lbPrecoFreio.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        lbPrecoFreio.setText("R$ 100.00");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel2.setText("Custo do Serviço");

        lbPrecoRadiador.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        lbPrecoRadiador.setText("R$ 350.00");

        lbPrecoOleo.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        lbPrecoOleo.setText("R$ 280.00");

        lbPrecoAlinhamento.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        lbPrecoAlinhamento.setText("R$ 120.00");

        lbPrecoEmbreagem.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        lbPrecoEmbreagem.setText("R$ 500.00");

        btCancelar.setBackground(new java.awt.Color(0, 0, 0));
        btCancelar.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        btAcessarPecas.setBackground(new java.awt.Color(0, 0, 0));
        btAcessarPecas.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btAcessarPecas.setForeground(new java.awt.Color(255, 255, 255));
        btAcessarPecas.setText("Peças Utilizadas");
        btAcessarPecas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAcessarPecasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btCancelar)
                .addGap(29, 29, 29)
                .addComponent(btAcessarPecas)
                .addGap(27, 27, 27))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbFreios)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(21, 21, 21)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(cbAlinhamento)
                                .addComponent(cbEmbreagem))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbAguaRadiador, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbPrecoRadiador)
                                    .addComponent(lbPrecoOleo)
                                    .addComponent(lbPrecoAlinhamento)
                                    .addComponent(lbPrecoFreio)
                                    .addComponent(lbPrecoEmbreagem))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbTrocaOleo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbServicos)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbServicos)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbFreios)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPrecoFreio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbAguaRadiador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPrecoRadiador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbTrocaOleo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPrecoOleo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbAlinhamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPrecoAlinhamento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbEmbreagem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPrecoEmbreagem))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCancelar)
                    .addComponent(btAcessarPecas))
                .addContainerGap(162, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbAguaRadiadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAguaRadiadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAguaRadiadorActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        dispose();

        FrameAcessoTelas acessoTela = new FrameAcessoTelas();
        acessoTela.setVisible(true);
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btAcessarPecasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAcessarPecasActionPerformed
        double valorRadiador = Double.parseDouble(cbAguaRadiador.getName());
        double valorFreio = Double.parseDouble(cbFreios.getName());
        double valorAlinhamento = Double.parseDouble(cbAlinhamento.getName());
        double valorEmbreagem = Double.parseDouble(cbEmbreagem.getName());
        double valorOleo = Double.parseDouble(cbTrocaOleo.getName());
        
        if(cbAguaRadiador.isSelected()) {
            Servicos servico = new Servicos();
            
            servico.setServico(cbAguaRadiador.getText());
            servico.setValor(BigDecimal.valueOf(valorRadiador));
            Controller.listaServicos.add(servico);
        }
        
        if(cbFreios.isSelected()) {
            Servicos servico2 = new Servicos();
            
            servico2.setServico(cbFreios.getText());
            servico2.setValor(BigDecimal.valueOf(valorFreio));
            Controller.listaServicos.add(servico2);
        }
        
        if(cbAlinhamento.isSelected()) {
            Servicos servico3 = new Servicos();
            
            servico3.setServico(cbAlinhamento.getText());
            servico3.setValor(BigDecimal.valueOf(valorAlinhamento));
            Controller.listaServicos.add(servico3);
        }
        
        
        if(cbEmbreagem.isSelected()) {
            Servicos servico4 = new Servicos();
            
            servico4.setServico(cbEmbreagem.getText());
            servico4.setValor(BigDecimal.valueOf(valorEmbreagem));
            Controller.listaServicos.add(servico4);
        }
        
        if(cbTrocaOleo.isSelected()) {
            Servicos servico5 = new Servicos();
            
            servico5.setServico(cbTrocaOleo.getText());
            servico5.setValor(BigDecimal.valueOf(valorOleo));
            Controller.listaServicos.add(servico5);
        }
        
        if (Controller.listaServicos.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Você precisa selecionar um Serviço", "ERRO!", JOptionPane.ERROR_MESSAGE);
        } else {
            
            JOptionPane.showMessageDialog(null, "Serviços cadastrados com Sucesso!");
            
            FrameDadosPecas dadosPecasTelas = new FrameDadosPecas();
            dadosPecasTelas.setVisible(true);
            
            dispose();
        }        
    }//GEN-LAST:event_btAcessarPecasActionPerformed

    private void cbEmbreagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEmbreagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEmbreagemActionPerformed

    private void cbFreiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFreiosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbFreiosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAcessarPecas;
    private javax.swing.JButton btCancelar;
    private javax.swing.JCheckBox cbAguaRadiador;
    private javax.swing.JCheckBox cbAlinhamento;
    private javax.swing.JCheckBox cbEmbreagem;
    private javax.swing.JCheckBox cbFreios;
    private javax.swing.JCheckBox cbTrocaOleo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lbPrecoAlinhamento;
    private javax.swing.JLabel lbPrecoEmbreagem;
    private javax.swing.JLabel lbPrecoFreio;
    private javax.swing.JLabel lbPrecoOleo;
    private javax.swing.JLabel lbPrecoRadiador;
    private javax.swing.JLabel lbServicos;
    private javax.swing.JTextPane tpDescricaoAlinhamento;
    private javax.swing.JTextPane tpDescricaoEmbreagem;
    private javax.swing.JTextPane tpDescricaoFreio;
    private javax.swing.JTextPane tpDescricaoRadiador;
    private javax.swing.JTextPane tpDescricaoTrocaOleo1;
    // End of variables declaration//GEN-END:variables
}
