/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ordemservico.view;

import com.mycompany.ordemservico.controller.Controller;
import com.mycompany.ordemservico.model.Pecas;
import java.math.BigDecimal;
import java.util.ArrayList;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author aluno
 */
public class FrameDadosPecas extends javax.swing.JFrame {

    /**
     * Creates new form FrameDadosPecas
     */
    public FrameDadosPecas() {
        initComponents();
        setLocationRelativeTo(this);
        Controller.listaPecas = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ckBiela = new javax.swing.JCheckBox();
        ckVelas = new javax.swing.JCheckBox();
        ckCorreia = new javax.swing.JCheckBox();
        ckLampada = new javax.swing.JCheckBox();
        ckSensor = new javax.swing.JCheckBox();
        ckSuspensao = new javax.swing.JCheckBox();
        lbValorBloco = new javax.swing.JLabel();
        lbValorVelas = new javax.swing.JLabel();
        lbValorCambio = new javax.swing.JLabel();
        lbValorPastilha = new javax.swing.JLabel();
        lbPistao = new javax.swing.JLabel();
        lbSuspensao = new javax.swing.JLabel();
        spBloco = new javax.swing.JSpinner();
        spVelas = new javax.swing.JSpinner();
        spCaixa = new javax.swing.JSpinner();
        spPastilha = new javax.swing.JSpinner();
        spPistao = new javax.swing.JSpinner();
        spSuspensao = new javax.swing.JSpinner();
        jSeparator1 = new javax.swing.JSeparator();
        btCancelar = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setText("PEÇAS UTILIZADAS");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel2.setText("Peças");

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel3.setText("Quantidade");

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel4.setText("Valor Unitário");

        ckBiela.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        ckBiela.setText("Biela Motor ");
        ckBiela.setName("165"); // NOI18N
        ckBiela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckBielaActionPerformed(evt);
            }
        });

        ckVelas.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        ckVelas.setText("Velas de ignição");
        ckVelas.setName("92"); // NOI18N

        ckCorreia.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        ckCorreia.setText("Kit Correia Dentada");
        ckCorreia.setName("125"); // NOI18N

        ckLampada.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        ckLampada.setText("Par de Lampadas Farol Baixo");
        ckLampada.setName("39"); // NOI18N

        ckSensor.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        ckSensor.setText("Sensor de Temperatura");
        ckSensor.setName("75"); // NOI18N
        ckSensor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckSensorActionPerformed(evt);
            }
        });

        ckSuspensao.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        ckSuspensao.setText("Kit Suspensão Fixa D/T");
        ckSuspensao.setName("899"); // NOI18N
        ckSuspensao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckSuspensaoActionPerformed(evt);
            }
        });

        lbValorBloco.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        lbValorBloco.setText("R$ 92.00");

        lbValorVelas.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        lbValorVelas.setText("R$ 165.00");

        lbValorCambio.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        lbValorCambio.setText("R$ 125.00");

        lbValorPastilha.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        lbValorPastilha.setText("R$ 39.00");

        lbPistao.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        lbPistao.setText("R$ 75.00");

        lbSuspensao.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        lbSuspensao.setText("R$ 899.00");

        spBloco.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        spBloco.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        spVelas.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        spVelas.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        spCaixa.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        spCaixa.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        spPastilha.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        spPastilha.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        spPistao.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        spPistao.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        spSuspensao.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        spSuspensao.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        btCancelar.setBackground(new java.awt.Color(0, 0, 0));
        btCancelar.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        btSalvar.setBackground(new java.awt.Color(0, 0, 0));
        btSalvar.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3)
                                        .addGap(114, 114, 114))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ckLampada)
                                            .addComponent(ckBiela)
                                            .addComponent(ckVelas)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(ckSuspensao)
                                                .addComponent(ckSensor))
                                            .addComponent(ckCorreia))
                                        .addGap(33, 33, 33)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(spCaixa, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                                            .addComponent(spVelas, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(spBloco)
                                            .addComponent(spPastilha)
                                            .addComponent(spPistao)
                                            .addComponent(spSuspensao))
                                        .addGap(19, 19, 19)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btSalvar)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lbValorCambio)
                                                .addComponent(lbValorVelas)
                                                .addComponent(lbValorPastilha)
                                                .addComponent(lbPistao)
                                                .addComponent(lbSuspensao)
                                                .addComponent(lbValorBloco))))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(btCancelar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(4, 4, 4)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ckVelas)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spVelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbValorBloco))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spBloco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbValorVelas)
                            .addComponent(ckBiela))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbValorCambio)
                            .addComponent(spCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ckCorreia))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ckLampada)
                                .addComponent(spPastilha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbValorPastilha))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ckSensor)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbPistao)
                                .addComponent(spPistao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spSuspensao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbSuspensao)
                            .addComponent(ckSuspensao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btSalvar)
                            .addComponent(btCancelar))
                        .addGap(14, 14, 14))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        dispose();
        
        FrameAcessoTelas acessoTela = new FrameAcessoTelas();
        acessoTela.setVisible(true);
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        int qtdBiela = (int) spBloco.getValue();
        int qtdCorreia = (int) spCaixa.getValue();
        int qtdLampada = (int) spPastilha.getValue();
        int qtdSensor = (int) spPistao.getValue();
        int qtdSuspensao = (int) spSuspensao.getValue();
        int qtdVelas = (int) spVelas.getValue();
        
        double valorBiela = Double.parseDouble(ckBiela.getName());
        double valorCorreia = Double.parseDouble(ckCorreia.getName());
        double valorLampada = Double.parseDouble(ckLampada.getName());
        double valorSensor = Double.parseDouble(ckSensor.getName());
        double valorSuspensao = Double.parseDouble(ckSuspensao.getName());
        double valorVelas = Double.parseDouble(ckVelas.getName());
        
        
            
        Object[][] componentes = {
            {ckBiela, qtdBiela, valorBiela},
            {ckLampada, qtdLampada, valorLampada},
            {ckCorreia, qtdCorreia, valorCorreia},
            {ckSensor, qtdSensor, valorSensor},
            {ckSuspensao, qtdSuspensao, valorSuspensao},
            {ckVelas, qtdVelas, valorVelas}
        };

        boolean checkboxSelecionada = false;
        boolean quantidadeSelecionada = false;

        for (Object[] componente : componentes) {
            Pecas peca = new Pecas();

            JCheckBox checkBox = (JCheckBox) componente[0];
            int quantidade = (int) componente[1];
            double valor = (double) componente[2];

            if (checkBox.isSelected()) {
                checkboxSelecionada = true;

                if (quantidade > 0) {
                     quantidadeSelecionada = true;
                     
                     peca.setNomePeca(checkBox.getText());
                     peca.setQtdPeca(quantidade);
                     peca.setValorUnitario(BigDecimal.valueOf(valor).multiply(BigDecimal.valueOf(quantidade)));
                } else {
                    JOptionPane.showMessageDialog(this, "Você precisa definir a quantidade de peças!", "ERRO!", JOptionPane.ERROR_MESSAGE);
                }

            }
            Controller.listaPecas.add(peca);
        }

        if (!checkboxSelecionada) {
            JOptionPane.showMessageDialog(this, "Nenhuma checkbox selecionada!", "ERRO!", JOptionPane.ERROR_MESSAGE);
        } 
        
        if (checkboxSelecionada && quantidadeSelecionada) {
            JOptionPane.showMessageDialog(null, "Peças cadastrada com Sucesso!");

           dispose();

           FrameAcessoTelas acessoTela = new FrameAcessoTelas();
           acessoTela.setVisible(true);   
        }
        
    }//GEN-LAST:event_btSalvarActionPerformed

    private void ckSuspensaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckSuspensaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckSuspensaoActionPerformed

    private void ckSensorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckSensorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckSensorActionPerformed

    private void ckBielaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckBielaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckBielaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JCheckBox ckBiela;
    private javax.swing.JCheckBox ckCorreia;
    private javax.swing.JCheckBox ckLampada;
    private javax.swing.JCheckBox ckSensor;
    private javax.swing.JCheckBox ckSuspensao;
    private javax.swing.JCheckBox ckVelas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbPistao;
    private javax.swing.JLabel lbSuspensao;
    private javax.swing.JLabel lbValorBloco;
    private javax.swing.JLabel lbValorCambio;
    private javax.swing.JLabel lbValorPastilha;
    private javax.swing.JLabel lbValorVelas;
    private javax.swing.JSpinner spBloco;
    private javax.swing.JSpinner spCaixa;
    private javax.swing.JSpinner spPastilha;
    private javax.swing.JSpinner spPistao;
    private javax.swing.JSpinner spSuspensao;
    private javax.swing.JSpinner spVelas;
    // End of variables declaration//GEN-END:variables
}
